Repository thoth-station/ttm-as-a-service, pull requests merged in 2022-08, with the labels that each got.

#2 init
  .aicoe-ci.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  LICENSE
  OWNERS
  Pipfile
  Pipfile.lock
  README.md
  app.py
  manifests/base/deploymentconfig.yaml
  manifests/base/kustomization.yaml
  manifests/base/route.yaml
  manifests/base/service.yaml
  ttm_github_pr.py
  wsgi.py
Labels: lgtm, size/XXL

#4 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: size/XS, approved, ok-to-test

#7 added version
  wsgi.py
Labels: size/XS, approved

#11 added overlays
  .aicoe-ci.yaml
  manifests/base/deploymentconfig.yaml
  manifests/base/imagestreamtag.yaml
  manifests/base/kustomization.yaml
  manifests/base/route.yaml
  manifests/base/service.yaml
  manifests/overlays/imagestreamtag.yaml
  manifests/overlays/kustomization.yaml
Labels: size/M, approved

#15 :turtle: Adjusted deployment as per flask app requirements
  .aicoe-ci.yaml
  .env.example
  README.md
  manifests/base/deploymentconfig.yaml
  manifests/base/route.yaml
  manifests/base/service.yaml
  manifests/overlays/test/imagestreamtag.yaml
  manifests/overlays/test/kustomization.yaml
  wsgi.py
Labels: size/M, approved

#20 added config
  gunicorn.conf.py
  manifests/base/deploymentconfig.yaml
  manifests/overlays/test/imagestreamtag.yaml
Labels: size/XS, approved
